const { ipcRenderer } = require('electron')
window.ZXNative = {
  startJob:p=>ipcRenderer.invoke('job:start',p),
  listJobs:()=>ipcRenderer.invoke('job:list'),
  cancelJob:id=>ipcRenderer.invoke('job:cancel',{id}),
  retryJob:id=>ipcRenderer.invoke('job:retry',{id}),
  listHistory:()=>ipcRenderer.invoke('history:list'),
  onJobChanged:fn=>ipcRenderer.on('job:changed',(_e,p)=>fn(p)),
  cacheInfo:()=>ipcRenderer.invoke('cache:info'),
  cacheClear:()=>ipcRenderer.invoke('cache:clear'),
  cacheSave:p=>ipcRenderer.invoke('cache:save',p),
  cacheChoose:()=>ipcRenderer.invoke('cache:choose'),
  installCodexMcp: (chooseLocation=false) => ipcRenderer.invoke('app:install-mcp',chooseLocation),
  reportPreview: (status) => ipcRenderer.send('preview:status',status),
  openWorldDialog: () => ipcRenderer.invoke('dialog:open-world'),
  openSchematicDialog: () => ipcRenderer.invoke('dialog:open-schematic'),
  chooseExportFolder: () => ipcRenderer.invoke('dialog:export-folder'),
  chooseCreateWorldFolder: () => ipcRenderer.invoke('dialog:create-world-folder'),
  chooseResourcePack: () => ipcRenderer.invoke('dialog:open-resource-pack'),
  autoDetectResourcePack: () => ipcRenderer.invoke('resource:auto-detect'),
  setResourcePack: (p) => ipcRenderer.invoke('resource:set', p),
  getResourceInfo: () => ipcRenderer.invoke('resource:info'),
  getTexture: (name) => ipcRenderer.invoke('resource:texture', name),
  loadWorld: (payload) => ipcRenderer.invoke('world:open', payload),
  createWorld: (payload) => ipcRenderer.invoke('world:create', payload),
  scanOverview: (payload) => ipcRenderer.invoke('world:scan-overview', payload),
  loadDetailBlocks: (payload) => ipcRenderer.invoke('world:detail-blocks', payload),
  executeTool: (name, payload) => ipcRenderer.invoke('world:tool', { name, payload }),
  projectGet: () => ipcRenderer.invoke('project:get'),
  projectUpdate: (patch) => ipcRenderer.invoke('project:update', patch),
  listMaterials: (box) => ipcRenderer.invoke('world:material-stats', box),
  exportSchematic: (payload) => ipcRenderer.invoke('world:export-schematic', payload),
  importSchematic: (payload) => ipcRenderer.invoke('world:import-schematic', payload),
  exportWorldCopy: (payload) => ipcRenderer.invoke('world:export-copy', payload),
  openPath: (target) => ipcRenderer.invoke('app:open-path', target),
  undo: () => ipcRenderer.invoke('world:undo'),
  redo: () => ipcRenderer.invoke('world:redo'),
  capturePreview: () => ipcRenderer.invoke('app:capture-preview'),
  getBridgeInfo: () => ipcRenderer.invoke('app:bridge-info'),
  onRefreshRequested: (fn) => ipcRenderer.on('bridge:refresh', (_e, data) => fn(data)),
  onFocusRequested: (fn) => ipcRenderer.on('bridge:focus', (_e, data) => fn(data)),
  onToast: (fn) => ipcRenderer.on('app:toast', (_e, data) => fn(data))
}
