const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict')
const {CacheManager,prepare}=require('../electron/cache-manager.cjs')
async function main(){
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'zx-cache-test-')),c=new CacheManager(path.join(temp,'user'),path.join(temp,'store'))
 const map=path.join(c.root,'maps','abc');fs.mkdirSync(map,{recursive:true})
 fs.writeFileSync(path.join(map,'overview-overworld-s1.json.gz'),'12345');fs.writeFileSync(path.join(map,'important.txt'),'keep')
 const world=path.join(temp,'world'),old=path.join(world,'.zxproject','cache');fs.mkdirSync(old,{recursive:true})
 fs.writeFileSync(path.join(old,'overview-overworld-s4.json.gz'),'123');fs.writeFileSync(path.join(world,'.zxproject','project.json'),'keep')
 assert.equal((await c.info(world)).total,8)
 assert.equal((await c.clear(world,true)).removed,0)
 const date=new Date(Date.now()-9*86400000);fs.utimesSync(path.join(map,'overview-overworld-s1.json.gz'),date,date)
 assert.equal((await c.clear(world,true)).removed,5)
 assert.equal((await c.clear(world)).removed,3)
 assert(fs.existsSync(path.join(map,'important.txt')));assert(fs.existsSync(path.join(world,'.zxproject','project.json')))
 c.save({parent:path.join(temp,'driveD'),auto:true,days:3,maxMB:64});assert((await c.info()).restart)
 const next=new CacheManager(path.join(temp,'user'),path.join(temp,'store'));assert(next.root.includes('driveD'));assert(next.settings.auto)
 assert.throws(()=>c.save({days:0}));const occupied=path.join(temp,'occupied','ZX-Cache');fs.mkdirSync(occupied,{recursive:true});fs.writeFileSync(path.join(occupied,'user.txt'),'keep');assert.throws(()=>prepare(path.dirname(occupied)))
 console.log('PASS: bytes, expiry, manual cleanup, preserve unrelated files, settings persistence, directory switch; fixture '+temp)
}
main().catch(e=>{console.error(e);process.exitCode=1})
